### PR TITLE
Respond with 204 OK + CORS to OPTIONS requests

### PR DESCRIPTION
**Pull request by theninj4**
I've refactored response headers a little to make it more consistent, and we're now responding with HTTP 204 instead of 404 for OPTIONS request. There's a new test to prevent any regressions.

### CODE REVIEW

**Comment by theninj4** [comment]
Resolves #94

**Comment by pmcnr-hx** [comment]
Code changes look good and tests pass: :+1:

**Comment by fabiobon** [comment]
I've tried to merge this pull but in browser there's one error. 
XMLHttpRequest cannot load http://localhost:16006/rest/articles. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
I've tried to put 
var client = new JsonapiClient("http://localhost:16006/rest", {  
	header: {
	    "Content-Type": "application/vnd.api+json",
	    "Accept": "application/vnd.api+json"
  	}
});
with no success.
Have you got any suggestion?
Thanx

**Comment by theninj4** [comment]
Thanks for taking a look @fabiobon - I was missing a CORS header, they should all be there now.

**Comment by theninj4** [comment]
I've tagged this as work-in-progress pending a client-side test suite for [jsonapi-client](https://github.com/holidayextras/jsonapi-client) to prove this PR solves our CORS issues.

**Comment by fabiobon** [comment]
Ok, after some tests configuration below works but, in browser, does not returns payload.body

  res.set({
    "Content-Type": "application/vnd.api+json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "*",
    "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept"
  });

  if (req.method === "OPTIONS") {
    return res.status(204).end();
  }

NOTE: to run in browser without cors erros I've replaced 
"Access-Control-Allow-Headers": "*"
with
"Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept"

**Comment by fabiobon** [comment]
Browser Only:
59. return callback(null, payload.body, payload.body.data, payload.body.included);
inside Transport._action retrives ERROR:
Uncaught TypeError: Cannot read property 'data' of null

**Comment by theninj4** [comment]
Thanks @fabiobon - I've fixed up this branch, it turns out we're not allowed to wildcard the `Access-Control-Allow-Headers` field, so I've resorted to simply reflecting what the client suggests. I've also had to lock down the `Access-Control-Allow-Methods`. This now resolves CORS issues, I've got a clientside test suite running for jsonapi-client in Firefox and Chrome against this branch :+1:

**Pull request merged**
