### PR TITLE
Allow some methods to be omitted from generated swagger docs

### PR DESCRIPTION
**Pull request by BryceCicada**
I have custom handlers that do not allow some operations on resources and/or relations.  I'd like the generated swagger docs to reflect this.

Here's my proposal.

### CODE REVIEW

**Comment by adamlc** [comment]
Interestingly I have certain methods disabled in my adapter disabled, i.e.

```nodejs
var jsonApi = require("jsonapi-server");

module.exports = new jsonApi.MemoryHandler();
module.exports.create = null;
module.exports.delete = null;
```

Shouldn't the swagger generator also pick those up? As it seems to put them in anyway :(

**Comment by pmcnr-hx** [comment]
@adamlc suggestion does appeal and it seems it would be simpler to implement. What do you think @BryceCicada: only add method to the swagger docs if it is defined in the handler?

**Comment by hpoom** [comment]
👍 to @adamlc implementation. I like that it is very clear in the code that those methods are not supported, instead of just forgotten about.

**Comment by theninj4** [comment]
The issue @BryceCicada was trying to solve here is the Swagger documentation of the individual JSON:API "routes" for mutating specific relationships. There are situations whereby we have a resource that can be updated, however it has one or more relationships that aren't modifiable by the API consumer - read only relationships. Right now, if a handler exposes update functionality, the Swagger doc generator will assume all relationships are open to modifications and will generate all the possible documentation. 

I've been sat on the fence with this change - I'm not convinced Swagger is the right tool for the job for documenting a JSON:API service, mainly because of issues like this one. I'm also undecided if jsonapi-server should validate attempts to update relationships via the same config as the docs. Basically I'm waiting until this becomes a problem for us in production, hoping that the experiences we're gaining on the journey lead us to an elegant solution.

**Comment by adamlc** [comment]
Makes sense I guess, as regards my comment shall I open another issue? I guess thats a little different to what @BryceCicada wants to achieve.

**Comment by pmcnr-hx** [comment]
@adamlc since the scope of your issue seems to be different, it's probably best to open a new issue.

**Comment by adamlc** [comment]
No problem, opened an issue in #190

**Pull request closed without merging**
