### PR TITLE
Use ES6 features

### PR DESCRIPTION
**Pull request by theninj4**
Convert the codebase to use all the new ES6 features. Automated via:
```
$ lebab --transform arrow,for-of,arg-spread,obj-method,no-strict,obj-shorthand,let,template,default-param --replace ./lib/
$ eslint --fix ./lib/
```
Again, if the build passes we should be good :+1:

### CODE REVIEW

**Comment by connormeredith** [comment]
👍

**Comment by theninj4** [comment]
Hmm so Node v4 errors with:

**Comment by theninj4** [comment]
So it looks like `node --use_strict` doesn't work with Mocha, so I'm now using `require('use-strict')` in the example server.

**Comment by theninj4** [comment]
That was a no-go either, now I'm trying `mocha --require use-strict`...

**Comment by theninj4** [comment]
Ahhh now Node v4 doesn't support array-spread. I'll close this and trim it a little.

**Pull request closed without merging**
