### PR TITLE
FIX: make Joi default() function work in jsonApi.define()

### PR DESCRIPTION
**Pull request by futurist**
PR for Issue: [#84](https://github.com/holidayextras/jsonapi-server/issues/84)

### CODE REVIEW

**Comment by theninj4** [comment]
Something odd seems to be going on here.

On the CI server, the tests fail with different date formats:
```
-    "timestamp": "2017-06-29T00:00:00.000Z"
+    "timestamp": "2017-06-29"
```

On my local machine, the same tests fail but they're an hour different:
```
-    "timestamp": "2017-06-28T23:00:00.000Z"
+    "timestamp": "2017-06-29"
```

This timestamp field is defined in example/resources/comments.js:13
```javascript
  timestamp: jsonApi.Joi.date().format("YYYY-MM-DD")
```

After poking around a bit, I've found we're passing around a date-string formatted as "2017-06-29" - this goes through Joi and gets converted to a javascript Date, which eventually gets converted back to JSON as it leaves the API, thus appearing as a full JSON timestamp regardless of the requested format. I'm guessing the time difference I'm seeing is timezone related?

**Comment by futurist** [comment]
also noticed that, firstly I think it's maybe moment.js lib issue, 
https://github.com/hapijs/joi/blob/master/lib/date.js#L74
but don't go deep at that moment.

if ISODate maybe it's will be OK?

**Comment by theninj4** [comment]
For reference - I'm in the UK, so I'm currently in the GMT timezone (GMT === UTC). During the summer months of the year we move into the BST timezone (BST === UTC+1). The difference in time is caused by the input date not containing a timezone (it's "2016-06-29", not "2016-06-29T00:00:00.000Z+000").

**Comment by theninj4** [comment]
Assuming the date's are correct, my next question is "why do the Date()s not conform to the requested format?".

Maybe the timestamp attribute should be re-typed to be `string`? It would at least prevent the type conversion from taking place. This might end up being a documentation note around what to expect when using the `Joi.date()` type. Or maybe we should steer clear of allowing Joi to convert types all together?

It's getting really late over here, I'm going to sleep on this one.

**Comment by futurist** [comment]
so moment.js convert user input into ISO Date

http://momentjs.com/docs/#/displaying/as-javascript-date/

Joi use it as below:

 `moment('2017-06-29', 'YYYY-MM-DD', true).toDate()`

the result output is 2017-06-28T23:00:00.000Z from the CI server according the timezone.

Date & time is complicated, so maybe it's better to pass it to Joi+Moment.js to manage and convert user input into more standard format?

**Comment by futurist** [comment]
I'm in China, the output is Thu Jun 29 2017 00:00:00 GMT+0800 (HKT), the same input date string, but if added to different timezone, it's different time.

**Comment by theninj4** [comment]
I think you're right, what it's doing is correct, it's the Joi validation defined in the comment resource that is wrong. Could you change the validation from a date to a string? It'd be great to add a new attribute (or alter an existing attribute) to contain a default value, then tweak one of the tests to ensure the default value is being applied correctly.

**Comment by futurist** [comment]
change to string() triggered many test case problems, so maybe solve the CI problems later.

**Pull request closed without merging**
